SELab-2/OSOC-2

docs/Domain Model/README.md, docs/Mock Ups/README.md, docs/conventions.md
Changed link from http link to relative
=> Fixed mock-ups link

backend/routes/github.ts
All GitHub routes now have function documentation.
Fixes #392
=> GitHub routes documentation

backend/orm_functions/session_key.ts, backend/routes/admin.ts, backend/routes/coach.ts, backend/routes/followup.ts, backend/routes/project.ts, backend/routes/role.ts, backend/routes/student.ts, backend/routes/template.ts, backend/routes/user.ts, backend/tests/orm_integration/session_key.test.ts, backend/tests/orm_unit/session_key.test.ts, backend/tests/utility.test.ts, backend/types.ts, backend/utility.ts, frontend/components/User/User.tsx, frontend/components/UserFilter/UserFilter.tsx, frontend/pages/students.tsx
=> Session key overhaul (backend side)

backend/config.json, backend/request.ts, backend/routes/admin.ts, backend/routes/coach.ts, backend/routes/followup.ts, backend/routes/project.ts, backend/routes/reset.ts, backend/routes/student.ts, backend/routes/user.ts, backend/routes/verify.ts, backend/tests/request.test.ts, docs/API/api.json
This pr contains a complete version of the api.json file. It follows the code on development (April 23, 2022, 00:31).
=> Update api json

backend/request.ts, backend/routes/form.ts, backend/types.ts
The unnecessary fields have been removed from the checks
=> Edit form route

backend/request.ts, frontend/contexts/sessionProvider.tsx, frontend/pages/reset/[pid].tsx
closes #460 
We had to generate new secrets + fix a redirect
=> fix: redirect for password reset works again

frontend/components/Header/Header.tsx, frontend/contexts/sessionProvider.tsx
buttons for student,... were visible when being on pending. This should now be resolved
=> buttons should be invisible when not signed in

frontend/pages/users.tsx
when you don't have admin privileges you should get redirected way from manage users
=> fix: redirect away from users when no admin

database/startupScripts/create_db.sql
=> feat: remove expired reset links #463

backend/request.ts
The email filter was broken (the filter didn't work when filtering on an invalid email address)
=> fix: student email filter

backend/config.json, backend/routes/admin.ts, backend/routes/coach.ts, backend/routes/user.ts, backend/tests/routes_unit/admin.test.ts, backend/tests/routes_unit/coach.test.ts, backend/tests/utility.test.ts, backend/types.ts, backend/utility.ts, database/startupScripts/generate_data.sql
=> Immutable admin [BE]

backend/orm_functions/orm_types.ts, backend/routes/user.ts
Change password is now possible in backend.
problems left: backend prints error when using invalid old password to try to reset
=> fix: only change password in user/self and also possible as coach

backend/routes/student.ts, backend/types.ts
The return value has been fixen of the `/student/<id>/suggest`
=> fix: create student suggestion return type

testforms/sendTestForms.sh, testforms/testform1.json, testforms/testform10.json, testforms/testform12.json, testforms/testform15.json, testforms/testform16.json, testforms/testform17.json, testforms/testform18.json, testforms/testform19.json, testforms/testform2.json, testforms/testform20.json, testforms/testform21.json, testforms/testform22.json, testforms/testform23.json, testforms/testform24.json, testforms/testform25.json, testforms/testform26.json, testforms/testform3.json, testforms/testform4.json, testforms/testform5.json, testforms/testform6.json, testforms/testform7.json, testforms/testform8.json, testforms/testform9.json
=> feat: new testdata

backend/routes/form.ts, backend/routes/user.ts
#500 A student can now go from a student to a login_user. In the database, this person will be a student and a login_user at the same time to show data from years ago.
=> Fix user student clash

backend/routes/student.ts, backend/types.ts, frontend/types.ts
This pr resolves the issues #515 and #516, the types should be good.
=> fix type issues

backend/orm_functions/orm_types.ts, backend/orm_functions/project.ts, backend/tests/orm_integration/project.test.ts, backend/tests/orm_unit/project.test.ts
=> Fix ormtests project

frontend/components/Settings/Settings.tsx
=> 2nd password input field user settings

backend/request.ts, backend/routes/project.ts, backend/tests/request.test.ts, backend/types.ts, docs/API/api.json
closes #537 Now, the return types in the project route contain the project roles.
=> Fix project roles

backend/tests/tests-setup.ts
This should fix the timeouts on github actions
=> fix: try to use the old timer for jest

backend/routes/template.ts, backend/tests/routes_unit/template.test.ts
100% coverage for template route
=> Template unit tests

backend/request.ts, frontend/pages/login/index.tsx, package-lock.json
Should fix the problem that we could no longer register.
=> fix: register works again

backend/package.json, backend/routes/coach.ts, backend/routes/login.ts, backend/tests/routes_unit/coach.test.ts, backend/tests/routes_unit/login.test.ts, backend/tests/routes_unit/verify.test.ts, package-lock.json
=> Coverage increase (coach, login)

backend/orm_functions/contract.ts, backend/orm_functions/orm_types.ts, backend/orm_functions/project.ts, backend/orm_functions/project_user.ts, backend/request.ts, backend/routes/project.ts, backend/tests/request.test.ts, backend/types.ts
This pr fixes the small route issues that were requested in this issue #596 
From now on you can change the project description, coaches, see the coach of the contract
=> Project route fixes

backend/orm_functions/osoc.ts, backend/request.ts, backend/routes/osoc.ts, backend/tests/orm_unit/osoc.test.ts, backend/tests/request.test.ts, backend/tests/routes_unit/osoc.test.ts, backend/types.ts, backend/utility.ts
=> Osoc Paging

.github/workflows/backendCI.yml
=> fix: try to fix the action by changing indentation

backend/routes/user.ts, backend/tests/routes_unit/user.test.ts, backend/types.ts, frontend/__tests__/SettingsComponent.test.tsx, frontend/__tests__/UserComponent.test.tsx, frontend/components/Settings/Settings.tsx, frontend/components/StudentOverview/StudentOverview.tsx, frontend/components/User/User.tsx, frontend/pages/settings.tsx, frontend/types.ts
The type of a login user in the frontend wasn't equal to a login user in the backend. This pull request fixes this bug.
=> fix: types of a login user in the frontend

frontend/components/Notification/Notification.module.scss, frontend/components/Notification/Notification.tsx, frontend/contexts/notificationProvider.module.scss, frontend/contexts/notificationProvider.tsx, frontend/pages/_app.tsx, frontend/pages/login/index.tsx, frontend/styles/globals.scss, frontend/types.ts
Having in app notifications allows us to show more information to the user when something succeeds or fails.
We will have three types of notifications:
=> feat(frontend): in app notifications

backend/routes/project.ts, backend/types.ts
There is now a generic student type
=> fix: student type

frontend/components/Header/Header.module.css
=> fix: increased padding-block for the header

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json
- removed passport
- removed types for bcrypt
- removed some types in the root
=> chore: remove some unused deps

frontend/components/Students/Students.tsx
The students url is now `http://localhost:3000/students?id=3` when a student is selected. So if you reuse this link you will get student with id 3 but only and only if that student is on the first results page.
=> feat: url for students

backend/tests/orm_unit/osoc.test.ts
The orm osoc file is fully covered.
=> fix: osoc orm test

backend/orm_functions/project.ts, backend/tests/orm_unit/project.test.ts
The orm project tests are done.
=> fix: project orm tests

backend/tests/orm_unit/project_user.test.ts
100% coverage for project_user
=> test: new test for orm project_user

backend/orm_functions/project.ts, backend/routes/project.ts, backend/routes/role.ts, frontend/components/Filters/ProjectFilter.tsx, frontend/components/Projects/Projects.tsx, frontend/types.ts
the filter now works as expected (not using the url to keep track of the parameters)
=> Project filter

backend/routes/project.ts, backend/tests/routes_unit/project.test.ts
This pull request contains new tests for the project route.
=> Fix project tests

backend/server.ts, backend/types.ts, backend/websocket_events/osoc.ts, frontend/components/Filters/OsocFilter.tsx, frontend/components/Osoc/Osoc.tsx, frontend/pages/osocs.tsx, frontend/pages/users.tsx, frontend/types.ts
Implemented basic event when creating or deleting osoc edition
=> feat: basic socket events for osoc editions

frontend/components/Notification/Notification.module.scss, frontend/components/ScrollView.module.scss, frontend/contexts/notificationProvider.tsx, frontend/pages/_app.tsx
=> fix: fixed z-index issues with notifs

frontend/components/StudentOverview/StudentOverview.module.scss, frontend/components/StudentOverview/StudentOverview.tsx
=> fix: update the final decision icon in the studentcard

backend/routes/project.ts, backend/tests/routes_unit/project.test.ts
=> fix: assign student bug

backend/tests/utility.test.ts
=> fix: utility test

backend/routes/followup.ts, backend/tests/routes_unit/followup.test.ts, frontend/components/StudentOverview/StudentOverview.module.scss, frontend/components/StudentOverview/StudentOverview.tsx
=> Follow up implementation
